// Exercise A5.2 - The Olive Jars
// Session: A5, exercise 2 of 7 (6 hours for the evaluation)
// Theme: chapter 10 (linear Diophantine equation via the extended
//   Euclidean algorithm; optimizing over the solution family)
// Tags: chapter-10, number-theory, modular-arithmetic, gcd
//
// MODEL: minimize x + y subject to ax + by = v with x, y >= 0
//   integers. This is a linear Diophantine equation; solvable iff
//   g = gcd(a, b) divides v. Dividing through by g leaves
//   a'x + b'y = v' with gcd(a', b') = 1, and the full solution family
//   is x = x0 + b't, y = y0 - a't over integer t.
// MATH: with a', b' coprime, x is determined modulo b': the valid x
//   are exactly x ≡ inv(a') * v' (mod b'), where inv comes from the
//   extended Euclidean algorithm. Let xmin be the smallest
//   non-negative representative; if a' * xmin > v' there is no
//   non-negative solution at all. Otherwise, one step t -> t + 1
//   raises x by b' and lowers y by a', so the count x + y is linear
//   in t with slope b' - a'. A linear function on an integer interval
//   is minimized at an endpoint, so only t = 0 (smallest x) and
//   t = t_max (largest x with y still >= 0) need evaluating.
// PROOF: family completeness is the standard Diophantine argument -
//   two solutions differ by a vector in the kernel of (a', b'), and
//   the kernel over the integers is generated by (b', -a') exactly
//   because gcd(a', b') = 1 (Bezout). Endpoint optimality is the
//   linearity observation above; no interior t needs checking.
// COMPLEXITY: O(log min(a, b)) for the two gcd computations;
//   everything else is constant. Memory O(1). The 6-hour trap is
//   trying to loop over jar counts: v / a can be 10^18.
// TYPES: v fits long long (<= 1e18 < 2^63). The dangerous products
//   are guarded by size: a', b' <= 1e6, xmin < b', so a' * xmin <=
//   1e12; b' * t_max <= v' by construction. The one product that
//   could overflow, inv * (v' mod b'), stays <= 1e6 * 1e6 = 1e12.
//   This is why the constraint says 1e6 and not 1e9: the statement is
//   quietly wearing chapter 01.
// ALTERNATIVES: BFS over reachable volumes (chapter 07) dies at
//   v = 1e18; coin-change DP (chapter 08) dies the same death; the
//   Chicken McNugget / Frobenius bound says nothing about minimality.
//   For TWO denominations the algebra above is exact and total.
// EDGE CASES: v = 0 (zero jars); a = b (forces v divisible by a);
//   v not divisible by gcd (impossible); divisible by gcd but no
//   non-negative split (impossible, e.g. a=5, b=3, v=7 has none);
//   v exactly one jar; b' = 1 (every residue allowed, xmin = 0).
//
// Compile: g++ -O2 -std=c++23 -Wall -Wextra -o jars a5-02-olive-jars.cpp

#include <cstdint>
#include <iostream>
#include <print>

namespace {

// Returns gcd(a, b) and Bezout coefficients x, y with a*x + b*y = g.
std::int64_t extended_gcd(std::int64_t a, std::int64_t b, std::int64_t& x, std::int64_t& y) {
    if (b == 0) {
        x = 1;
        y = 0;
        return a;
    }
    std::int64_t x1 = 0;
    std::int64_t y1 = 0;
    const std::int64_t g = extended_gcd(b, a % b, x1, y1);
    x = y1;
    y = x1 - (a / b) * y1;
    return g;
}

}  // namespace

int main() {
    std::ios_base::sync_with_stdio(false);
    std::cin.tie(nullptr);

    std::int64_t a = 0;
    std::int64_t b = 0;
    std::int64_t v = 0;
    std::cin >> a >> b >> v;

    std::int64_t bezout_a = 0;
    std::int64_t bezout_b = 0;
    const std::int64_t g = extended_gcd(a, b, bezout_a, bezout_b);
    if (v % g != 0) {
        std::println("impossible");
        return 0;
    }

    const std::int64_t ra = a / g;  // a' and b', coprime
    const std::int64_t rb = b / g;
    const std::int64_t rv = v / g;

    // Smallest non-negative x with ra * x ≡ rv (mod rb). bezout_a is
    // inv(ra) mod rb up to sign; both factors are reduced below 1e6
    // before multiplying, so the product fits comfortably.
    std::int64_t xmin = 0;
    if (rb > 1) {
        const std::int64_t inv = ((bezout_a % rb) + rb) % rb;
        xmin = (inv * (rv % rb)) % rb;
    }

    if (ra * xmin > rv) {  // ra * xmin <= 1e12: safe
        std::println("impossible");
        return 0;
    }

    const std::int64_t y_at_xmin = (rv - ra * xmin) / rb;
    const std::int64_t count_low_x = xmin + y_at_xmin;

    const std::int64_t t_max = (rv - ra * xmin) / (ra * rb);
    const std::int64_t xmax = xmin + rb * t_max;
    const std::int64_t y_at_xmax = y_at_xmin - ra * t_max;
    const std::int64_t count_high_x = xmax + y_at_xmax;

    std::println("{}", count_low_x < count_high_x ? count_low_x : count_high_x);
    return 0;
}
