// Exercise T03.4 - The Apothecary's Doses
// Session: T03.S3, exercise 2 of 2 (1 hour for both)
// Theme: chapter 03 (std::expected: the reason for failure is part of the
//   result; validation order)
// Tags: chapter-03
//
// MODEL: each line either parses as `a/b` with b > 0, yielding the
//   truncated quotient, or fails with one of two distinguishable reasons.
// MATH: the format is a tiny grammar: optional minus, digits, '/', digits,
//   end of line. Validation must run in grammar order: a malformed line
//   has no meaningful b, so `bad format` is decided before `division by
//   zero` can even be asked. The quotient itself is C++ integer division,
//   which truncates toward zero: -9/2 = -4, matching the statement.
// PROOF: the parser accepts exactly the strings generated by the grammar
//   (each character class is checked once, and trailing garbage is
//   rejected by the end-of-line test). For accepted lines, hardware
//   division implements the truncation contract directly.
// COMPLEXITY: O(length) per line; O(q * 40) total. Memory O(1) per line.
// TYPES: |a| <= 1e15 and b <= 1e15 fit in long long with room to spare;
//   the magnitude check during parsing rejects overlong digit runs before
//   they overflow the accumulator (at most 16 digits accepted).
// ALTERNATIVES: std::optional<long long> could report failure but not
//   which failure, and the shop's rule demands the reason; exceptions
//   centralize the error path but hide it from the type. The
//   std::expected<long long, std::string_view> return makes both outcomes
//   visible at the call site, which is the Chapter 3 lesson.
// EDGE CASES: `7/0` (well-formed, refused for the divisor); `3x/2` and
//   `/4` and `5/` and an empty line (bad format); negative a with exact
//   and inexact division; b = 1; the maximum magnitudes.
//
// Compile (LLVM): clang++-23 -std=c++23 -stdlib=libc++ -O2 -Wall -Wextra -o doses t03-s3-2-apothecary-doses.cpp
// Compile (MSVC): cl /std:c++latest /O2 /EHsc /W4 /permissive- /Zc:__cplusplus /Fedoses.exe t03-s3-2-apothecary-doses.cpp

#include <expected>
#include <iostream>
#include <print>
#include <string>
#include <string_view>

struct Dose {
    long long a;
    long long b;
};

std::expected<Dose, std::string_view> parse(std::string_view line) {
    std::size_t i = 0;
    bool negative = false;
    if (i < line.size() && line[i] == '-') { negative = true; ++i; }

    auto digits = [&](long long& out) -> bool {
        std::size_t start = i;
        out = 0;
        while (i < line.size() && line[i] >= '0' && line[i] <= '9') {
            if (i - start >= 16) return false;  // longer than any valid value
            out = out * 10 + (line[i] - '0');
            ++i;
        }
        return i > start;
    };

    long long a = 0;
    long long b = 0;
    if (!digits(a)) return std::unexpected("bad format");
    if (i >= line.size() || line[i] != '/') return std::unexpected("bad format");
    ++i;
    if (!digits(b)) return std::unexpected("bad format");
    if (i != line.size()) return std::unexpected("bad format");

    if (b == 0) return std::unexpected("division by zero");
    return Dose{negative ? -a : a, b};
}

int main() {
    int q = 0;
    std::cin >> q;
    std::cin.ignore();  // consume the end of the first line

    std::string line;
    while (q-- > 0) {
        std::getline(std::cin, line);
        auto dose = parse(line);
        if (dose)
            std::print("{}/{} = {}\n", dose->a, dose->b, dose->a / dose->b);
        else
            std::print("REFUSED {}\n", dose.error());
    }
    return 0;
}
