// Exercise T09.6 - The Gossip Circuit
// Session: T09.S4, exercise 2 of 3 (2 hours for the three)
// Theme: chapter 09 (strongly connected components, Kosaraju,
//   iterative DFS)
// Tags: chapter-09, dfs
//
// MODEL: circles of trust are strongly connected components: maximal
//   vertex sets where every ordered pair is connected by a directed
//   path. Mutual reachability is an equivalence relation on a
//   digraph's vertices; SCCs are its classes, and the answer is the
//   number of classes.
// MATH: Kosaraju's two passes. Pass 1: DFS the graph, recording
//   vertices in order of FINISH time. Pass 2: DFS the REVERSED graph,
//   starting from the latest finisher not yet claimed; each second-
//   pass tree claims exactly one SCC. Count the trees.
// PROOF: the condensation (SCCs contracted) is a DAG. In pass 1, the
//   SCC containing the latest overall finish time is a SOURCE of the
//   condensation (a DFS that enters a non-source SCC finishes it
//   before the SCC that reaches it finishes). In the reversed graph,
//   that source becomes a sink, so the pass-2 DFS from the latest
//   finisher reaches exactly its own SCC - nothing else is reachable
//   from a sink. Remove it and induct: each pass-2 root claims
//   precisely one component. Both passes visit each vertex and edge
//   once.
// COMPLEXITY: O(n + m) time, O(n + m) memory for the graph plus its
//   reverse. Tarjan does it in one pass without the reversed graph;
//   Kosaraju is chosen for the transparency of its proof - in a
//   contest, the algorithm you can re-derive is the one you can
//   debug.
// TYPES: ids and counters fit int. The real hazard is stack depth:
//   recursive DFS dies politely at 2e5 on a path graph, so both
//   passes run an EXPLICIT stack with a per-vertex edge cursor - the
//   pattern is worth owning once and reusing forever.
// ALTERNATIVES: Tarjan (one pass, low-link bookkeeping); the
//   path-based algorithm (two stacks, equally one-pass). For the mere
//   COUNT all are equivalent; for condensation edges or member lists,
//   any of them extends. DSU does not work: mutual reachability is
//   not generated by symmetric unions.
// EDGE CASES: m = 0 (n circles); the whole town one cycle (1);
//   self-channel a == a (singleton unless on a larger cycle);
//   parallel channels; a long path (n circles - and the explicit
//   stack's reason to exist).
//
// Compile (LLVM): clang++-23 -std=c++23 -stdlib=libc++ -O2 -Wall -Wextra -o gossip t09-s4-2-gossip-circuit.cpp
// Compile (MSVC): cl /std:c++latest /O2 /EHsc /W4 /permissive- /Zc:__cplusplus /Fegossip.exe t09-s4-2-gossip-circuit.cpp

#include <iostream>
#include <print>
#include <vector>

namespace {

// Iterative DFS over adj from s; appends vertices to finish_order in
// finish-time order if record_finish, marks seen.
void dfs(int s, const std::vector<std::vector<int>>& adj, std::vector<bool>& seen,
         std::vector<int>* finish_order) {
    std::vector<std::pair<int, std::size_t>> stack;  // (vertex, next edge index)
    seen[static_cast<std::size_t>(s)] = true;
    stack.emplace_back(s, 0);
    while (!stack.empty()) {
        auto& [u, cursor] = stack.back();
        const auto& edges = adj[static_cast<std::size_t>(u)];
        if (cursor < edges.size()) {
            const int v = edges[cursor++];
            if (!seen[static_cast<std::size_t>(v)]) {
                seen[static_cast<std::size_t>(v)] = true;
                stack.emplace_back(v, 0);
            }
        } else {
            if (finish_order != nullptr) finish_order->push_back(u);
            stack.pop_back();
        }
    }
}

}  // namespace

int main() {
    std::ios_base::sync_with_stdio(false);
    std::cin.tie(nullptr);

    int n = 0;
    int m = 0;
    std::cin >> n >> m;

    std::vector<std::vector<int>> forward(static_cast<std::size_t>(n) + 1);
    std::vector<std::vector<int>> reverse(static_cast<std::size_t>(n) + 1);
    for (int e = 0; e < m; ++e) {
        int a = 0;
        int b = 0;
        std::cin >> a >> b;
        forward[static_cast<std::size_t>(a)].push_back(b);
        reverse[static_cast<std::size_t>(b)].push_back(a);
    }

    // Pass 1: finish order on the forward graph.
    std::vector<bool> seen(static_cast<std::size_t>(n) + 1, false);
    std::vector<int> finish_order;
    finish_order.reserve(static_cast<std::size_t>(n));
    for (int s = 1; s <= n; ++s) {
        if (!seen[static_cast<std::size_t>(s)]) dfs(s, forward, seen, &finish_order);
    }

    // Pass 2: reversed graph, latest finisher first; one tree per circle.
    std::fill(seen.begin(), seen.end(), false);
    int circles = 0;
    for (auto it = finish_order.rbegin(); it != finish_order.rend(); ++it) {
        if (!seen[static_cast<std::size_t>(*it)]) {
            ++circles;
            dfs(*it, reverse, seen, nullptr);
        }
    }

    std::print("{}\n", circles);
    return 0;
}
